Repository surendratalk/lodge-website-design, pull requests merged in 2022-10, with the labels that each got.

#2 Create hotel.html
  hotel.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#1 Add files via upload
  about.html
  contact.html
  css/bootstrap.css
  css/responsive.css
  css/style.css
  css/style.css.map
  css/style.scss
  fonts/Poppins/OFL.txt
  fonts/Poppins/Poppins-Bold.ttf
  fonts/Poppins/Poppins-Regular.ttf
  fonts/ethnocentric/ethnocentric rg it.ttf
  fonts/ethnocentric/ethnocentric rg.ttf
  fonts/ethnocentric/read-this.html
  fonts/ethnocentric/typodermic-eula-02-2014.pdf
  images/about-img.png
  images/cart.png
  images/client.png
  images/design-1.png
  images/design-2.png
  images/fb.png
  images/hero-bg.png
  images/i-1.png
  images/i-2.png
  images/i-3.png
  images/insta.png
  images/linkedin.png
  images/location.png
  images/logo.png
  images/mail.png
  images/menu.png
  images/next-black.png
  images/next.png
  images/p-1.png
  images/phone.png
  images/prev-black.png
  images/prev.png
  images/ring-img.jpg
  images/search-icon.png
  images/slider-img.png
  images/twitter.png
  index.html
  jewellery.html
  js/bootstrap.js
  js/custom.js
  js/jquery-3.4.1.min.js
Labels: help wanted, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#3 Update hotel.html
  hotel.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#4 Create lodge-site.html
  lodge-site.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#5 Create newpage.html
  newpage.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#6 Create proton.html
  proton.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#8 Create motel-city.html
  motel-city.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
